VARIABLE_START_SECTION = "WAKE UP"
METHOD_START_SECTION = "EVERYDAY I WAKE UP"
MAIN_LOOP_SECTION = "PIECE OF SHIT"
END_LOOP_SECTION = "FUCK THIS SHIT"

REQUIRED_SECTIONS = {
    MAIN_LOOP_SECTION: False
}

OPTIONAL_SECTIONS = {
    VARIABLE_START_SECTION: False,
    METHOD_START_SECTION: False,
    END_LOOP_SECTION: False
}

COMMENTS = "#"

LIBS_LOCATION = "libs"